version: 2.1
jobs:
  r-test-cimg:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install rust
          command: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: rustup target add wasm32-unknown-unknown
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Build Docker container
          command: docker build . -t filecoin/builtin-actors
      - run:
          name: Install IPFS
          command: |
            curl -O https://dist.ipfs.tech/kubo/v0.16.0/kubo_v0.16.0_linux-amd64.tar.gz
            tar -xvzf kubo_v0.16.0_linux-amd64.tar.gz
            pushd kubo
            sudo bash install.sh
            popd
            rm -rf kubo
      - run:
          name: Reproducibility test
          command: ./scripts/test-reproducibility.sh
      - run:
          name: Print results
          command: echo "$(cat cid-results.txt)"
workflows:
  version: 2
  r-test:
    jobs:
      - r-test-cimg
